name: Move VKR to root

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  move:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Move VKR contents to repository root
        run: |
          rsync -a VKR/ ./
          rm -rf VKR

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Move VKR contents to repository root"
          git push
