name: Unpack VKR.zip

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download ZIP from release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p /tmp/vkr
          gh release download update \
            --pattern "VKR.zip" \
            --dir /tmp/vkr

      - name: Unpack archive
        run: |
          unzip -o "/tmp/vkr/VKR.zip" -d .

      - name: Commit unpacked files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "Unpack VKR.zip"
            git push
          fi
